# https://github.com/domluna/JuliaFormatter.jl

# Annotates fields in a type definitions with ::Any if no type annotation is provided
annotate_untyped_fields_with_any = false

# Transforms a short function definition to a long function definition if the short
# function definition exceeds the maximum margin.
short_to_long_function_def = true

# Transforms a long function definition to a short function definition if the short
# function definition does not exceed the maximum margin.
long_to_short_function_def = true